[[redirects]]
  from = "/blog-backend/*"
  to = "http://139.224.206.212:8090/:splat"
  status = 200
  force = false
[[redirects]]
  from = "/proxy/*"
  to = "http://ipv6.mjczy.top:10810/:splat"
  status = 200
  force = false
[[redirects]]
  from = "/zachary/*"
  to = "https://www.zzacharyzz.fun/:splat"
  status = 200
  force = false
  headers = {Host = "www.zzacharyzz.fun", X-Forwarded-Host = "www.zzacharyzz.fun"}
[[redirects]]
  from = "/pic/*"
  to = "/pic/:splat"
  status = 200
  force = false
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false